title        = "tttardigrado"
languageCode = "pt-pt"
paginate     = 10

[params]
  desc = "computer science, hip-hop, debate e esquerdalhices variadas"
  lang = ["pt", "en"]
  socials = [ 
    { url = "https://www.instagram.com/ttttardigrado/", name = "insta" }
  , { url = "https://github.com/tttardigrado", name = "git" }
  ]
